apiversion: apps/v1
kind: Deployment
metadata:
  name: deployment name
  namespace: given the name space
spec: 
  replicas: 2
  selector:
    matchLables:
      app: monogodb
  template:
    matadata:
      name: deploymentpodname
      labels:
        app: monogodb
    spec:
      containers:
      - name: mongodbcontainer
        image: mrrowdy/imagenamemongoimagename
        ports:
        - containerPort: 8080
          resources:
            requests: 
              cpu: 500m
              memory: 256m
            limits:
              cpu: 1gb
              memory: 500m
          env: 
          - name: MONGO_DB_HOSTNAME
            value: mongodbsvc
          - name: MONGO_DB_USEERNAME
            value: devdb
          - name: MONGO_DB_PASSWORD
            value: devdb@123
---
#create service with deployment
apiVersion: v1
kind: Service
metadata:
  name: servicename
spec: 
  selector: 
    app: mongodb 
  ports:
  - port: 80
    targetP8ort: 8080
---
#created the mongodb using contianerimage
apiversion: apps/v1
kind: deployment
metadata:
  name: mongodbdeployment
spec:  
  replicas: 1
  selector:
    matchLables: 
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: container name mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: devdb
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: devdb@123
        volumemounts:
        - name: given the name
          mountPath: /data/db/
      volumes:
      - name: given the volume name
        hostpath: 
          path: givrn the path
# using nfs file storage
      volumes:
      - name: given the name 
        nfs:
          server: given the server ip adress 
          path: given the nfs path 
#using with persuistentvolumeclaim
      volumes:
      PersistentVolumeClaim:
        claimName: mongopvc

#createpvc
apiversion: v1 
kind: PersistentVolumeClaim
metadata:
  name: mongopvc
spec: 
  accessmode:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

#createpv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv
spec:
  capacity:
    storage: 1gi
  accessModes:
  - ReadWriteOnce
  nfs: 
    server: ip adress
    path: 

--- 
#cretae service with mongodb
apiVersion: v1
kind: Service
metadata:
  name: mongodbsvc
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
