name: Sync multiple branches
on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/fabianMendez/privatemodule
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@master

      - name: Merge Development -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: Development
          target_branch: staging
          github_token: ${{ github.token }}
          
      - name: Merge staging -> uat
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: staging
          target_branch: uat
          github_token: ${{ github.token }}
      -  run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      
      - name: Merge uat -> QA
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: uat
          target_branch: QA
          github_token: ${{ github.token }}
          
      - name: Merge QA -> main
        uses: devmasx/merge-branch@master
        with:
          type: now
          form_branch: QA
          target_branch: main
          github_token: ${{ github.token }}
